apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: loki-reader
rules:
- apiGroups:
  - loki.grafana.com
  resourceNames:
  - logs
  resources:
  - application
  - infrastructure
  - audit
  verbs:
  - get
