apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: loki-bucket
  labels:
  {{ include "mychart.labels" . }}
spec:
  generateBucketName: loki-bucket
  storageClassName: openshift-storage.noobaa.io