{{/* @TODO - Convert to data source configuration file */}}
{{/* @SEE https://grafana.com/docs/grafana/latest/administration/provisioning/#example-data-source-configuration-file */}}
{{- if .Values.datasources.enabled -}}
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus-datasource
  namespace: {{ include "grafana-instance.namespace" . }}
  labels:
    {{- include "grafana-instance.labels" . | nindent 4 }}
spec:
  {{- include "grafana-instance.commonValues" . | nindent 2 }}
  valuesFrom:
    - targetPath: "secureJsonData.httpHeaderValue1"
      valueFrom:
        secretKeyRef:
          name: {{ printf "%s-auth-token" (include "grafana-instance.serviceAccountName" $) | quote }}
          key: token
  datasource:
    name: Prometheus
    type: prometheus
    access: proxy
    url: https://thanos-querier.openshift-monitoring.svc:9091
    isDefault: true
    editable: false
    secureJsonData:
      httpHeaderValue1: 'Bearer ${token}'
    jsonData:
      httpHeaderName1: 'Authorization'
      tlsSkipVerify: true
      timeInterval: "5s"
{{- end }}