apiVersion: tempo.grafana.com/v1alpha1
kind: TempoMonolithic
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: tempo-tls
  name: {{ include "mychart.name" . }}
  namespace: {{ include "mychart.namespace" . }}
spec:
  management: {{ .Values.tempoMonolithic.management }}
  resources:
    limits:
      memory: 2Gi
      cpu: 2000m
  storage:
    traces:
      backend: s3
      s3:
        tls:
          enabled: true
          caName: openshift-service-ca.crt
        secret: tempo-secret
      size: {{ .Values.tempoMonolithic.storage.size | default "1Gi" }}

  extraConfig:
    tempo:
      metrics_generator:
        processor:
          local_blocks:
            filter_server_spans: false
          span_metrics:
            dimensions:
              - service_name
              - operation
              - status_code

        traces_storage:
          path: /var/tempo/generator/traces
        storage:
          path: /var/tempo/generator/wal
          remote_write:
          - url: http://mimir-instance-nginx.mimir-instance.svc/api/v1/write
            send_exemplars: true
      overrides:
        defaults:
          metrics_generator:
            processors: [service-graphs, span-metrics]

  jaegerui:
    enabled: false
  ingestion:
    otlp:
      grpc:
        enabled: true
      http:
        enabled: true
  query:
    rbac:
      enabled: true
  multitenancy:
    mode: openshift
    enabled: true
