apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tempostack-traces-reader
  namespace: {{ include "mychart.namespace" . }}
  {{ include "mychart.labels" . }}
roleRef:
  kind: ClusterRole
  name: tempo-reader
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  apiGroup: rbac.authorization.k8s.io
  name: system:authenticated
