apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tempostack-traces-write
  namespace: {{ include "mychart.namespace" . }}
  {{ include "mychart.labels" . }}
rules:
- apiGroups:
    - 'tempo.grafana.com'
  resources:
    - application
    - infrastructure
    - audit
  resourceNames:
    - traces
  verbs:
    - 'create'
