apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-collector-logs-writer
  labels:
    {{- include "mychart.labels" . | nindent 4 }}
rules:
  - apiGroups:
    - 'loki.grafana.com'
    resources:
    - application
    - infrastructure
    - audit
    resourceNames:
    - logs
    verbs:
    - 'create'
    - 'get'
  - apiGroups:
    - ""
    resources:
    - pods
    - namespaces
    - nodes
    verbs:
    - 'get'
    - 'list'
    - 'watch'
  - apiGroups:
    - 'apps'
    resources:
    - replicasets
    verbs:
    - 'get'
    - 'list'
    - 'watch'
