apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mimir-cluster-reader
rules:
- apiGroups:
  - "*"
  resources:
  - pods
  - services
  - endpoints
  - namespaces
  verbs:
  - get
  - list
  - watch