apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mimir-cluster-reader-binding
subjects:
- kind: ServiceAccount
  name: {{ include "mimir-instance.name" . }}-sa
  namespace: {{ include "mimir-instance.namespace" . }}
roleRef:
  kind: ClusterRole
  name: mimir-cluster-reader
  apiGroup: rbac.authorization.k8s.io
