apiVersion: v1
kind: Secret
metadata:
  name: mimir-secret
  namespace: {{ include "mimir-instance.namespace" . }}
  labels:
    {{ include "mimir-instance.labels" . | nindent 4 }}
stringData:
  bucket: "mimir-bucket"
  endpoint: "http://s3.openshift-storage.svc"
{{/*  replace with values from mimir-bucket secret, then seal*/}}
  access_key_id: "my-access-key-id"
  access_key_secret: "my-access-key-secret"
---
apiVersion: v1
kind: Secret
metadata:
  name: mimir-blocks-secret
  namespace: {{ include "mimir-instance.namespace" . }}
  labels:
    {{ include "mimir-instance.labels" . | nindent 4 }}
stringData:
  blocks_bucket: "mimir-blocks-bucket"
  blocks_endpoint: "http://s3.openshift-storage.svc"
{{/*  replace with values from mimir-blocks-bucket secret, then seal*/}}
  blocks_access_key_id: "my-access-key-id"
  blocks_access_key_secret: "my-access-key-secret"