{{- $domain := (include "dex.clusterDomain" .) -}}
{{- $dexIssuer := (printf "https://dex-%s.apps.%s/dex" (include "dex.namespace" .) $domain) -}}
{{/* Environment Variables is supported and expanded */}}
apiVersion: v1
kind: Secret
metadata:
  name: dex-config
  namespace: {{ include "dex.namespace" . }}
  labels:
    {{- include "dex.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.yaml: |-
    issuer: {{ $dexIssuer }}
    storage:
      type: kubernetes
      config:
        inCluster: true

    connectors:
    - type: openshift
      id: openshift
      name: Login with OpenShift
      config:
        issuer: {{ printf "https://api.%s:6443" $domain }}
        clientID: system:serviceaccount:{{ include "dex.namespace" . }}:{{ .Values.dex.serviceAccount.name }}
        clientSecret: $SA_TOKEN
        redirectURI: {{ printf "%s/callback" $dexIssuer }}
        {{- if .Values.allowedGroups }}
        # Optional list of required groups a user must be a member of
        groups:
          {{- range $_, $value := .Values.allowedGroups }}
          - {{ $value | quote }}
          {{- end }}
        {{- end }}
    oauth2:
      skipApprovalScreen: true

    staticClients:
    - id: grafana-otel
      redirectURIs:
      - {{ printf "https://%s-%s.apps.%s/login/generic_oauth" .Values.grafana.routeName .Values.grafana.namespace $domain }}
      name: 'Grafana'
      {{/* Must match `spec.config[auth.generic_oauth].client_secret` in Grafana */}}
      secret: 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef

