apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-token" .Values.dex.serviceAccount.name }}
  namespace: {{ include "dex.namespace" . }}
  labels:
    {{- include "dex.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ .Values.dex.serviceAccount.name }}
type: kubernetes.io/service-account-token
