grafana:
  name: grafana-instance
  domain: mlkb012t.stakater.cloud
  instance:
    sessionSecret: "R%Jfjsdiojfsd+89cu8UY\/()(Y8'''423HIODFSDFAPÅ+O23U893767&%/()=&FYGV()/&TRGVsafs4d65fas4()/T&(UIGJK)"
    labels:
      app: grafana-otel
  dex:
    enabled: true
    issuer: dex-dex-instance
    client_id: "grafana-otel"
    client_secret: "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
resyncPeriod: 0m30s
tenants:
  - abc123
dashboards:
  enabled: false
datasources:
  enabled: true
folders:
  enabled: true
